const host = "http://localhost:5000";
export const registerRoute = `${host}/auth/register`;
export const loginRoute = `${host}/auth/login`;
export const updateRoomRoute = `${host}/auth/update`;
export const createRoomRoute = `${host}/room/create`;
export const joinRoomRoute = `${host}/room/join`;
export const getAllRoomRoute = `${host}/room/all`;
export const getRoomNameRoute = `${host}/room/name`;
export const END_POINT = `http://localhost:5000`;
